<?php

$wp_terms = array(
  array('term_id' => '1','name' => 'Uncategorized','slug' => 'uncategorized','term_group' => '0'),
  array('term_id' => '2','name' => 'simple','slug' => 'simple','term_group' => '0'),
  array('term_id' => '3','name' => 'grouped','slug' => 'grouped','term_group' => '0'),
  array('term_id' => '4','name' => 'variable','slug' => 'variable','term_group' => '0'),
  array('term_id' => '5','name' => 'external','slug' => 'external','term_group' => '0'),
  array('term_id' => '6','name' => 'exclude-from-search','slug' => 'exclude-from-search','term_group' => '0'),
  array('term_id' => '7','name' => 'exclude-from-catalog','slug' => 'exclude-from-catalog','term_group' => '0'),
  array('term_id' => '8','name' => 'featured','slug' => 'featured','term_group' => '0'),
  array('term_id' => '9','name' => 'outofstock','slug' => 'outofstock','term_group' => '0'),
  array('term_id' => '10','name' => 'rated-1','slug' => 'rated-1','term_group' => '0'),
  array('term_id' => '11','name' => 'rated-2','slug' => 'rated-2','term_group' => '0'),
  array('term_id' => '12','name' => 'rated-3','slug' => 'rated-3','term_group' => '0'),
  array('term_id' => '13','name' => 'rated-4','slug' => 'rated-4','term_group' => '0'),
  array('term_id' => '14','name' => 'rated-5','slug' => 'rated-5','term_group' => '0'),
  array('term_id' => '15','name' => 'Uncategorized','slug' => 'uncategorized','term_group' => '0'),
  array('term_id' => '16','name' => 'Main Menu','slug' => 'main-menu','term_group' => '0'),
  array('term_id' => '17','name' => 'Buttweld','slug' => 'buttweld','term_group' => '0'),
  array('term_id' => '18','name' => 'Flange','slug' => 'flange','term_group' => '0'),
  array('term_id' => '19','name' => 'Tri-Clamp','slug' => 'tri-clamp','term_group' => '0'),
  array('term_id' => '20','name' => 'SED Diaphragm Valves','slug' => 'sed-diaphragm-valves','term_group' => '0'),
  array('term_id' => '31','name' => 'Valves','slug' => 'valves','term_group' => '0'),
  array('term_id' => '22','name' => '304 (1.4301)','slug' => '304-1-4301','term_group' => '0'),
  array('term_id' => '23','name' => '304 (1.4306)','slug' => '304-1-4306','term_group' => '0'),
  array('term_id' => '24','name' => '316 (1.4401)','slug' => '316-1-4401','term_group' => '0'),
  array('term_id' => '25','name' => '316L (1.4404)','slug' => '316l-1-4404','term_group' => '0'),
  array('term_id' => '26','name' => '316L (1.4435)','slug' => '316l-1-4435','term_group' => '0'),
  array('term_id' => '27','name' => '904L (1.4539)','slug' => '904l-1-4539','term_group' => '0'),
  array('term_id' => '28','name' => '316Ti (1.4571)','slug' => '316ti-1-4571','term_group' => '0'),
  array('term_id' => '29','name' => 'C22 (2.4602)','slug' => 'c22-2-4602','term_group' => '0'),
  array('term_id' => '32','name' => 'Fittings','slug' => 'fittings','term_group' => '0'),
  array('term_id' => '33','name' => 'Seals','slug' => 'seals','term_group' => '0'),
  array('term_id' => '34','name' => 'Pumps &amp; Mixers','slug' => 'pumps-mixers','term_group' => '0'),
  array('term_id' => '35','name' => 'Sealers &amp; Welders','slug' => 'sealers-welders','term_group' => '0'),
  array('term_id' => '36','name' => 'Transfers','slug' => 'transfers','term_group' => '0'),
  array('term_id' => '37','name' => 'Hoses','slug' => 'hoses','term_group' => '0'),
  array('term_id' => '38','name' => 'Validation &amp; Gauges','slug' => 'validation-gauges','term_group' => '0'),
  array('term_id' => '39','name' => 'Pressure safety','slug' => 'pressure-safety','term_group' => '0'),
  array('term_id' => '40','name' => 'Single Use','slug' => 'single-use','term_group' => '0'),
  array('term_id' => '41','name' => 'Ball valves','slug' => 'ball-valves','term_group' => '0'),
  array('term_id' => '42','name' => 'Diaphragm valves','slug' => 'diaphragm-valves','term_group' => '0'),
  array('term_id' => '43','name' => 'Butterfly valves','slug' => 'butterfly-valves','term_group' => '0'),
  array('term_id' => '44','name' => 'Check valves','slug' => 'check-valves','term_group' => '0'),
  array('term_id' => '45','name' => 'Control valves','slug' => 'control-valves','term_group' => '0'),
  array('term_id' => '46','name' => 'Pinch valves','slug' => 'pinch-valves','term_group' => '0'),
  array('term_id' => '47','name' => 'Actuators','slug' => 'actuators','term_group' => '0'),
  array('term_id' => '48','name' => 'Actuator','slug' => 'actuator','term_group' => '0'),
  array('term_id' => '49','name' => 'Manual','slug' => 'manual','term_group' => '0'),
  array('term_id' => '50','name' => '1','slug' => '1','term_group' => '0'),
  array('term_id' => '51','name' => '2','slug' => '2','term_group' => '0'),
  array('term_id' => '52','name' => '3','slug' => '3','term_group' => '0'),
  array('term_id' => '53','name' => '4','slug' => '4','term_group' => '0'),
  array('term_id' => '54','name' => '5','slug' => '5','term_group' => '0'),
  array('term_id' => '55','name' => '6','slug' => '6','term_group' => '0'),
  array('term_id' => '56','name' => '7','slug' => '7','term_group' => '0'),
  array('term_id' => '57','name' => '8','slug' => '8','term_group' => '0'),
  array('term_id' => '58','name' => '9','slug' => '9','term_group' => '0'),
  array('term_id' => '59','name' => '10','slug' => '10','term_group' => '0'),
  array('term_id' => '60','name' => 'Adaptors','slug' => 'adaptors','term_group' => '0'),
  array('term_id' => '61','name' => 'Ferrules','slug' => 'ferrules','term_group' => '0'),
  array('term_id' => '62','name' => 'ASME BPE Fittings','slug' => 'asme-bpe-fittings','term_group' => '0'),
  array('term_id' => '63','name' => 'Blind plates','slug' => 'blind-plates','term_group' => '0'),
  array('term_id' => '64','name' => 'Kest-Lock','slug' => 'kest-lock','term_group' => '0'),
  array('term_id' => '65','name' => 'Ingold','slug' => 'ingold','term_group' => '0'),
  array('term_id' => '66','name' => 'TK &amp; NA connect','slug' => 'tk-na-connect','term_group' => '0'),
  array('term_id' => '67','name' => 'Push fittings','slug' => 'push-fittings','term_group' => '0'),
  array('term_id' => '68','name' => 'Staubli','slug' => 'staubli','term_group' => '0'),
  array('term_id' => '69','name' => 'Hose tails','slug' => 'hose-tails','term_group' => '0'),
  array('term_id' => '70','name' => 'Tri-clamps','slug' => 'tri-clamps','term_group' => '0'),
  array('term_id' => '71','name' => 'Seals &amp; O-rings','slug' => 'seals-o-rings','term_group' => '0'),
  array('term_id' => '72','name' => 'Torque tools','slug' => 'torque-tools','term_group' => '0'),
  array('term_id' => '73','name' => 'Diaphragm pumps','slug' => 'diaphragm-pumps','term_group' => '0'),
  array('term_id' => '74','name' => 'Sealers','slug' => 'sealers','term_group' => '0'),
  array('term_id' => '75','name' => 'Welders','slug' => 'welders','term_group' => '0'),
  array('term_id' => '76','name' => 'Ezi-Dock transfer systems','slug' => 'ezi-dock-transfer-systems','term_group' => '0'),
  array('term_id' => '77','name' => 'Mousehole transferport','slug' => 'mousehole-transferport','term_group' => '0'),
  array('term_id' => '78','name' => 'Iris valve','slug' => 'iris-valve','term_group' => '0'),
  array('term_id' => '79','name' => 'Cut blind plates','slug' => 'cut-blind-plates','term_group' => '0'),
  array('term_id' => '80','name' => 'Hoses','slug' => 'hoses-hoses','term_group' => '0'),
  array('term_id' => '81','name' => 'Tubing','slug' => 'tubing','term_group' => '0'),
  array('term_id' => '82','name' => 'Crimp fittings','slug' => 'crimp-fittings','term_group' => '0'),
  array('term_id' => '83','name' => 'Hose accessories','slug' => 'hose-accessories','term_group' => '0'),
  array('term_id' => '84','name' => 'Pressure meters','slug' => 'pressure-meters','term_group' => '0'),
  array('term_id' => '85','name' => 'Flow meters','slug' => 'flow-meters','term_group' => '0'),
  array('term_id' => '86','name' => 'Monster sampling','slug' => 'monster-sampling','term_group' => '0'),
  array('term_id' => '87','name' => 'Safety valves','slug' => 'safety-valves','term_group' => '0'),
  array('term_id' => '88','name' => 'Rupture disc','slug' => 'rupture-disc','term_group' => '0'),
  array('term_id' => '89','name' => 'Pressure control valves','slug' => 'pressure-control-valves','term_group' => '0'),
  array('term_id' => '90','name' => 'Single use systems','slug' => 'single-use-systems','term_group' => '0'),
  array('term_id' => '91','name' => 'Singe use sets','slug' => 'singe-use-sets','term_group' => '0'),
  array('term_id' => '92','name' => 'Single use fittings &amp; clamps','slug' => 'single-use-fittings-clamps','term_group' => '0'),
  array('term_id' => '93','name' => '1TEST','slug' => '1test','term_group' => '0'),
  array('term_id' => '94','name' => 'Orbital welding','slug' => 'orbital-welding','term_group' => '0'),
  array('term_id' => '95','name' => 'Threaded','slug' => 'threaded','term_group' => '0'),
  array('term_id' => '96','name' => 'Swagelock','slug' => 'swagelock','term_group' => '0'),
  array('term_id' => '97','name' => 'NA Connect','slug' => 'na-connect','term_group' => '0'),
  array('term_id' => '98','name' => 'Hosebarb','slug' => 'hosebarb','term_group' => '0'),
  array('term_id' => '99','name' => 'Socket Weld','slug' => 'socket-weld','term_group' => '0'),
  array('term_id' => '100','name' => 'ASME-BPE','slug' => 'asme-bpe','term_group' => '0'),
  array('term_id' => '101','name' => 'BS-4825','slug' => 'bs-4825','term_group' => '0'),
  array('term_id' => '102','name' => 'DIN 11850','slug' => 'din-11850','term_group' => '0'),
  array('term_id' => '103','name' => 'ISO 1127','slug' => 'iso-1127','term_group' => '0'),
  array('term_id' => '104','name' => 'SMS 3008','slug' => 'sms-3008','term_group' => '0'),
  array('term_id' => '105','name' => 'Casted','slug' => 'casted','term_group' => '0'),
  array('term_id' => '106','name' => 'Forged','slug' => 'forged','term_group' => '0'),
  array('term_id' => '107','name' => 'SF1','slug' => 'sf1','term_group' => '0'),
  array('term_id' => '108','name' => 'SF2','slug' => 'sf2','term_group' => '0'),
  array('term_id' => '109','name' => 'SF3','slug' => 'sf3','term_group' => '0'),
  array('term_id' => '110','name' => 'SF4','slug' => 'sf4','term_group' => '0'),
  array('term_id' => '111','name' => 'SF5','slug' => 'sf5','term_group' => '0'),
  array('term_id' => '112','name' => 'SF6','slug' => 'sf6','term_group' => '0'),
  array('term_id' => '113','name' => 'Mixers','slug' => 'mixers','term_group' => '0'),
  array('term_id' => '114','name' => 'Diaphragms','slug' => 'diaphragms','term_group' => '0'),
  array('term_id' => '116','name' => 'Steam','slug' => 'steam','term_group' => '0'),
  array('term_id' => '117','name' => 'Sight glasses','slug' => 'sight-glasses','term_group' => '0')
);

foreach( $wp_terms as $row ):
  if( $row['term_id'] == '100' ):
    echo $row['name'];
  endif;
endforeach;
 
?>